FROM node:22-alpine AS builder

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build
CMD ["node", "--watch", "build/app.js"]

FROM node:22-alpine AS runner

# Install curl
RUN apk add --no-cache curl

WORKDIR /app
COPY package*.json ./
RUN npm ci --omit=dev
COPY --from=builder /app/build ./build
COPY --from=builder /app/docs ./docs

EXPOSE 3000
CMD ["node", "./build/app.js"]